import { ArrowUpRight, MapPin, Phone } from 'lucide-react';
import logo from '../img/logo_evergreen.webp';
export default function Footer({ setView } = {}) {
  function go(event, view) { if (!setView || event.metaKey || event.ctrlKey || event.shiftKey || event.altKey) return; event.preventDefault(); setView(view); }
  return <footer id="contacts" className="shop-footer"><div className="shop-container">
    <div className="shop-footer-grid"><div className="shop-footer-about"><img src={logo} alt="Evergreen coffee" width="130" height="84" /><p>Кава та щоденні покупки поруч.<br />Замовляйте онлайн, забирайте в нашій кав’ярні.</p></div><div><p className="shop-eyebrow">ЗАВІТАЙТЕ ДО НАС</p><a className="shop-footer-address" href="https://www.google.com/maps/search/?api=1&query=%D0%9A%D0%B8%D1%97%D0%B2%2C%20%D0%91%D1%96%D0%BB%D0%B8%D1%86%D1%8C%D0%BA%D0%B0%2020" target="_blank" rel="noopener noreferrer"><MapPin size={19} /> Київ, Білицька, 20 <ArrowUpRight size={17} /></a><p>Щодня · 09:00–21:00</p><a href="tel:+380997592367" className="shop-footer-address"><Phone size={17} /> +380 99 759 23 67</a></div><div className="shop-footer-links"><p className="shop-eyebrow">ЗАВЖДИ НА ЗВ’ЯЗКУ</p><a href="https://t.me/EvergreeenCofee" target="_blank" rel="noopener noreferrer">Telegram <ArrowUpRight size={16} /></a><a href="https://instagram.com/evergreen___coffee/" target="_blank" rel="noopener noreferrer">Instagram <ArrowUpRight size={16} /></a><a href="/how-it-works" onClick={event => go(event, 'how-it-works')}>Як це працює? <ArrowUpRight size={16} /></a></div></div>
    <div className="shop-footer-bottom"><span>© {new Date().getFullYear()} Evergreen coffee</span><span>Кава · маркет · поруч</span><a href="/catalog" onClick={event => go(event, 'catalog')}>До каталогу ↗</a></div>
  </div></footer>;
}
